### ISSUE TITLE
Can't receive Inbound SMS 

### ISSUE THREAD

**Issue by SmartManoj** [LiveHelperChat/twilio#9]
PHP Version 7.2
Prefixed number with `whatsapp:`
```
[20-Oct-2020 20:29:07 Asia/Kolkata] Exception: Invalid recipient in /home/helpfuldotnet/public_html/chatbot/extension/twilio/bootstrap/bootstrap.php:610
Stack trace:
#0 /home/helpfuldotnet/public_html/chatbot/cache/compiledtemplates/4f30eb016ce809098e0fc0e06f873835.php(2): erLhcoreClassExtensionTwilio->processCallback(Array)
#1 /home/helpfuldotnet/public_html/chatbot/lib/core/lhcore/lhmodule.php(96): include('/home/helpfuldo...')
#2 /home/helpfuldotnet/public_html/chatbot/lib/core/lhcore/lhmodule.php(555): erLhcoreClassModule::runModule()
#3 /home/helpfuldotnet/public_html/chatbot/index.php(49): erLhcoreClassModule::moduleInit()
#4 {main}
[20-Oct-2020 20:32:23 Asia/Kolkata] PHP Deprecated:  Function create_function() is deprecated in /home/helpfuldotnet/public_html/chatbot/extension/twilio/vendor/twilio-php-master/Services/Twilio/Resource.php on line 93
```

**Comment by SmartManoj** [comment]
Not added prefix for phone.
What is Base phone number?

**Comment by remdex** [comment]
Just in that case not whole phone number would be shown in the chat. Without base number. So just do not enter base phone number and have full phone number and leave empty base phone number.
